const log = document.querySelector('#log');
const launch = document.querySelector('#launch');
const stateLabel = document.querySelector('#state');
const message = document.querySelector('#message');
const choices = [...document.querySelectorAll('.choices button')];
const operatives = [...document.querySelectorAll('.operative')];
const difficultyButtons = [...document.querySelectorAll('[data-difficulty]')];
const squad = { VOSS: { hp: 88, max: 88 }, MORROW: { hp: 64, max: 64 }, 'SABLE-9': { hp: 42, max: 42 } };
const actions = {
  breach: { title: 'Plasma volley', hint: 'Spend ammunition for heavy damage.', damage: 31, ammo: 18, focus: -6, recoil: 8 },
  ghost: { title: 'Measured fire', hint: 'Conserve supplies and stay mobile.', damage: 19, ammo: 6, focus: 2, recoil: 4 },
  signal: { title: 'Decode the chorus', hint: 'Risk focus to expose a weak point.', damage: 25, ammo: 0, focus: -12, recoil: 2 },
  guard: { title: 'Brace formation', hint: 'Recover focus and reduce next hit.', damage: 5, ammo: 0, focus: 9, recoil: 1 },
  suppress: { title: 'Suppress the nest', hint: 'Area fire disrupts the next attack.', damage: 23, ammo: 22, focus: -2, recoil: 3 },
  medicae: { title: 'Field medicae', hint: 'Restore the selected operative.', damage: 0, ammo: 8, focus: 5, heal: 24, recoil: 0 },
  relic: { title: 'Relic discharge', hint: 'A single devastating charge.', damage: 52, ammo: 0, focus: -18, recoil: 0 }
};
const profiles = { casual: { label: 'CASUAL', enemyHit: 7, reward: 220 }, standard: { label: 'STANDARD', enemyHit: 12, reward: 340 }, iron: { label: 'IRONMAN', enemyHit: 17, reward: 620 } };
let career = JSON.parse(localStorage.getItem('iron-meridian-career') || '{"rank":1,"credits":0,"wins":0}');
let game = { phase: 'ready', enemy: 100, round: 0, focus: 72, ammo: 64, relic: true, selected: 'VOSS', guarded: false, difficulty: localStorage.getItem('iron-meridian-difficulty') || 'standard' };
function addLog(who, text, warning = false) { const entry = document.createElement('p'); entry.className = warning ? 'warn' : ''; entry.innerHTML = `<time>${new Date().toLocaleTimeString([], { hour12: false })}</time><span><b>${who}</b> ${text}</span>`; log.append(entry); log.scrollTop = log.scrollHeight; }
function clamp(value) { return Math.max(0, Math.min(100, value)); }
function updateCareer() { document.querySelector('#rank').textContent = String(career.rank).padStart(2, '0'); document.querySelector('#credits').textContent = `${career.credits} CREDITS`; localStorage.setItem('iron-meridian-career', JSON.stringify(career)); }
function updateReserves() { const values = document.querySelectorAll('.resource>strong'); if (values[0]) values[0].textContent = `${game.focus}%`; if (values[1]) values[1].textContent = `${game.ammo}%`; const bars = document.querySelectorAll('.bar i'); if (bars[0]) bars[0].style.width = `${game.focus}%`; if (bars[1]) bars[1].style.width = `${game.ammo}%`; operatives.forEach((operative) => { const unit = squad[operative.dataset.name]; operative.querySelector('em').textContent = unit.hp; operative.querySelector('u').style.width = `${(unit.hp / unit.max) * 100}%`; }); }
function renderBattleMessage(title, copy) { message.innerHTML = `<b>${game.round || '+'}</b><span><strong>${title}</strong><small>${copy}</small><small style="display:block;color:#e27766;margin-top:10px;font-family:'Space Mono'">RELAY WARDEN &nbsp; ${game.enemy}%</small><i style="display:block;width:${game.enemy}%;height:5px;background:#e27766;margin-top:4px"></i></span>`; }
function setChoices(enabled, list) { choices.forEach((button, index) => { const action = list[index]; button.disabled = !enabled || !action; button.dataset.choice = action || ''; button.querySelector('strong').textContent = action ? actions[action].title : 'Awaiting orders'; button.querySelector('small').textContent = action ? actions[action].hint : 'Unavailable'; }); }
function beginOperation() { game = { phase: 'combat', enemy: 100, round: 1, focus: 72, ammo: 64, relic: true, selected: 'VOSS', guarded: false, difficulty: game.difficulty }; Object.values(squad).forEach((unit) => { unit.hp = unit.max; }); launch.innerHTML = 'OPERATION LIVE <strong>&rarr;</strong>'; stateLabel.textContent = `${profiles[game.difficulty].label} // ROUND 1`; renderBattleMessage('The relay warden wakes.', 'Three heat signatures converge. Select an action for the squad.'); setChoices(true, ['breach', 'ghost', 'signal', 'guard', 'suppress', 'medicae']); updateReserves(); addLog('COMMAND', `${profiles[game.difficulty].label} profile loaded. Drop confirmed.`, true); }
function finishOperation(won) { game.phase = won ? 'victory' : 'defeat'; stateLabel.textContent = won ? 'RELAY SECURED' : 'SQUAD LOST'; setChoices(false, []); if (won) { const reward = profiles[game.difficulty].reward; career.credits += reward; career.wins += 1; career.rank = 1 + Math.floor(career.wins / 2); updateCareer(); renderBattleMessage('Signal core recovered.', `Operation complete. +${reward} credits awarded. Career rank ${career.rank}.`); document.querySelector('.objective em').textContent = '1 / 1'; addLog('COMMAND', `Victory confirmed. ${reward} credits transferred.`); } else { renderBattleMessage('The relay consumes the light.', 'All squad coherence is gone. Reset the operation and try a different approach.'); addLog('COMMAND', 'Operation failed. No signal returned.', true); } launch.innerHTML = 'RESTART OPERATION <strong>&rarr;</strong>'; launch.onclick = beginOperation; }
function resolveAction(choice) { if (game.phase !== 'combat') return; const move = actions[choice]; if (choice === 'relic' && !game.relic) return; if (move.ammo > game.ammo) { addLog('SYSTEM', 'Insufficient ammunition for that action.', true); return; } game.round += 1; game.ammo = clamp(game.ammo - move.ammo); game.focus = clamp(game.focus + move.focus); if (choice === 'relic') game.relic = false; const actor = squad[game.selected]; if (move.heal) { actor.hp = clamp(actor.hp + move.heal); addLog(game.selected, `${move.title} restores ${move.heal} health.`); } else { game.enemy = clamp(game.enemy - move.damage); actor.hp = clamp(actor.hp - (game.guarded ? 2 : move.recoil)); addLog(game.selected, `${move.title} lands for ${move.damage} damage.`); } game.guarded = choice === 'guard' || choice === 'suppress'; if (game.enemy <= 0) { updateReserves(); finishOperation(true); return; } const enemyHit = game.guarded ? 4 : profiles[game.difficulty].enemyHit + (game.round % 3); actor.hp = clamp(actor.hp - enemyHit); game.focus = clamp(game.focus - (game.guarded ? 0 : 4)); updateReserves(); if (Object.values(squad).every((unit) => unit.hp <= 0) || game.focus <= 0) { finishOperation(false); return; } stateLabel.textContent = `${profiles[game.difficulty].label} // ROUND ${game.round}`; renderBattleMessage('The warden returns fire.', `${game.selected} takes ${enemyHit} damage. Choose the squad's next move.`); setChoices(true, game.relic ? ['breach', 'guard', 'suppress', 'signal', 'medicae', 'relic'] : ['breach', 'guard', 'suppress', 'signal', 'medicae', 'ghost']); }
launch.onclick = beginOperation; choices.forEach((button) => button.addEventListener('click', () => resolveAction(button.dataset.choice))); operatives.forEach((operative) => operative.addEventListener('click', () => { operatives.forEach((item) => item.classList.remove('active')); operative.classList.add('active'); game.selected = operative.dataset.name; if (game.phase === 'combat') addLog(game.selected, 'Formation acknowledged. Awaiting vector.'); })); difficultyButtons.forEach((button) => button.addEventListener('click', () => { difficultyButtons.forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); game.difficulty = button.dataset.difficulty; localStorage.setItem('iron-meridian-difficulty', game.difficulty); addLog('COMMAND', `${profiles[game.difficulty].label} profile selected.`); })); document.querySelector('#clear').onclick = () => { log.innerHTML = '<p><time>--:--:--</time><span><b>SYSTEM</b> Transmission log cleared.</span></p>'; }; document.querySelector('#sound').onclick = (event) => { event.currentTarget.textContent = event.currentTarget.textContent === '×' ? '♫' : '×'; }; updateCareer(); if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js'));
